### ISSUE TITLE
README.md 

### ISSUE THREAD

**Issue by j-lord** [pcdslab/Fast-GPU-PCC#1]
Just had a quick question, in the last line of the readme file it says that 

- Example of an input file is having **5 voxels with time series of length 4** is shown in example_data.txt

But in example_data.txt the date shown is
3.44 2.35 7.69
7.66 4.38 2.3434
6.77 8.88 7.87
1.22 4.33 5.54
5.44 1.44 24.53

Are these not **5 voxels with time series of length 3?**
Thanks! Great paper!

**Comment by pcdslab** [comment]
Yes, that is an example of 5 voxels with time series of length 3. I corrected the readme file.

Thanks for the note!
