### ISSUE TITLE
no kernel image is available for execution on the device GPU_side.cu

### ISSUE THREAD

**Issue by jamesruffle** [pcdslab/Fast-GPU-PCC#3]
I have read your paper on Fast-GPU-PCC with great interest and hope to apply it to some models. I note that in your paper, you described using Cuda 7.5.

I am running Cuda 10.1, Ubuntu 18.04. However, when running the code with the example data, I run into the following error:

`no kernel image is available for execution on the device GPU_side.cu`

I am guessing that this relates to the version of Cuda used in your paper being older than I have installed. Yet, I am unable to install Cuda 7.5, as NVIDIA did not release this for the later Ubuntu operating systems (my machine is running 18.04). Please could you clarify if you know of a fix to get your toolkit running with later versions of Cuda? The algorithm looks immensely powerful and I would love to be able to use it in my research, if it is feasible…!

Thanks for your time.
James

**Comment by mgawan** [comment]
the author has built the code for NVIDIA K-40 devices, looks like you have a more recent GPU device. You will need to change these flags **-arch=compute_35 -code=sm_35** in accordance with the architecture of your device.

**Comment by jamesruffle** [comment]
You are right. For Ubuntu 18.04, Cuda 10.1, changing the compilation to 

`nvcc -lcublas -O2 -arch=compute_75 -code=sm_75 -std=c++11 CPU_side.cpp GPU_side.cu -o exec
`
has solved the issue. Many thanks!
