### ISSUE TITLE
CPU only implementation

### ISSUE THREAD

**Issue by chipet** [pcdslab/Fast-GPU-PCC#5]
In your paper, you present a comparison with a CPU only implementation. 
Would it be possible to add the CPU only implementation to your repository or to point towards its location ?

**Comment by pcdslab** [comment]
If you read our preliminary paper entitled "GPU-PCC: A GPU Based Technique to Compute Pairwise
Pearson’s Correlation Coefficients for Big fMRI Data" you will see that we used the CPU version of the program that was implemented by Wang et al 2013.

I am sharing their code repository (which is also refereed to our paper above) below for your reference:

https://github.com/BNAplatform-organization/PAGANI-toolkit/tree/master/src/BNAPlatform-win64-cuda7.0-20151118/src/CorMat

Prof. S.
